#!/usr/bin/env bash
# Press a Dreamcast button in flycast, by NAME, without stealing focus.
#
#   scripts/dc-keys.sh start            # one press
#   scripts/dc-keys.sh a 3 800 120      # 3 presses, 800 ms apart, 120 ms held
#
# Thin wrapper over flycast-send-key.ps1, whose parameters are a Windows
# virtual-key code and a PC scancode -- neither of which is what you know when
# you want to press "A". The table below is the missing translation, and it is
# not guessable: flycast maps SDL scancodes, so the binding file names 40 for
# Start and 27 for A, which are Return and the X key, whose Windows codes are
# 0x0D/0x1C and 0x58/0x2D.
#
# The mapping is read out of flycast's own binding file rather than assumed:
#   build/RelWithDebInfo/mappings/SDL_Clavier.cfg
#     bind9 = 40:btn_start        SDL 40 = Return
#     bind8 = 27:btn_a            SDL 27 = X
#     bind2 =  6:btn_b            SDL  6 = C
#     bind6 = 25:btn_x            SDL 25 = V
#     bind0/7/26/22 = analog left/right/up/down   -> A D W S
#     bind13..16 = 79..82 dpad right/left/down/up -> arrow keys
# If that file is re-generated by flycast's input GUI, re-read it; the numbers
# here will not follow it on their own.
#
# WHY POSTMESSAGE AND NOT SendKeys: see the header of flycast-send-key.ps1.
# SendKeys was measured to do nothing from a non-interactive shell.
#
# Pairs with `dc-screen.py --probe`, which answers "did that do anything" in
# ~0.2 s without producing an image.
set -u
cd "$(dirname "$0")/.."

declare -A VK=(
  [start]=0x0D [a]=0x58 [b]=0x43 [x]=0x56
  [up]=0x57 [down]=0x53 [left]=0x41 [right]=0x44
  [dup]=0x26 [ddown]=0x28 [dleft]=0x25 [dright]=0x27
)
declare -A SC=(
  [start]=0x1C [a]=0x2D [b]=0x2E [x]=0x2F
  [up]=0x11 [down]=0x1F [left]=0x1E [right]=0x20
  [dup]=0x48 [ddown]=0x50 [dleft]=0x4B [dright]=0x4D
)

KEY="${1:-}"
if [[ -z "$KEY" || -z "${VK[$KEY]:-}" ]]; then
  echo "usage: $0 <key> [count] [delay_ms] [hold_ms]" >&2
  echo "keys: ${!VK[*]}" >&2
  echo "  start a b x            buttons" >&2
  echo "  up down left right     analog stick (WASD)" >&2
  echo "  dup ddown dleft dright d-pad (arrow keys)" >&2
  exit 2
fi

powershell.exe -NoProfile -ExecutionPolicy Bypass \
  -File "$(wslpath -w scripts/flycast-send-key.ps1)" \
  -Count "${2:-1}" -DelayMs "${3:-1200}" -HoldMs "${4:-90}" \
  -Vk "${VK[$KEY]}" -Scan "${SC[$KEY]}" 2>&1 \
  | tr -d '\r' | grep -E "sent=|NO_FLYCAST|NO_WINDOW_HANDLE"
