#!/usr/bin/env python3
"""Fold DreamShell's per-game preset files into one table the host can carry.

WHAT THIS IS FOR

A retail title decides for itself which parts of RAM it treats as free, and
several of them treat the hole dcload sits in as exactly that. DreamShell
answers that question title by title, in the `memory` field of its isoldr
presets, and those 2054 files are the accumulated result of people getting
these specific games to run. dcload-ip-rs reads the table this script produces
to pick which relinked loader to chainload before it uploads a game.

WHY A TABLE AND NOT THE FILES

The presets are one 176-byte file per game PER DEVICE (`cd_`, `sd_`, `ide_`),
which is 2054 files to ship and parse. Measured across all of them, the three
device variants of a game NEVER disagree about `memory` -- only about `async`
(921 games) and `dma` (939), both of which describe the loader's own storage
device and mean nothing on a network transport. So one row per game, taken
from the `cd` variant, loses nothing we could act on.

THE KEY IS DreamShell'S OWN MD5, AND IT WILL OFTEN MISS

The file names are the MD5 of the disc's boot sector: 2048 bytes read at the
first sector of the data track (fs_iso9660.c, ISOFS_IOCTL_GET_BOOT_SECTOR_DATA
-> read_data(session_base - 150, 1, ...)). That is a hash of IP.BIN sector 0,
so it identifies a specific dump, not a game -- and coverage is partial: of the
1027 distinct hashes here, neither of the two Sonic Adventure dumps on this
machine is present. 25 of the entries are the MD5 of 2048 zero bytes
(c99a74c555371a433d121f551d6c6398), i.e. presets saved from a boot-sector read
that failed, which is worth knowing before trusting a hash match blindly.

So the table also carries the IP.BIN title, and the host falls back to matching
on that. Titles are not unique either -- 24 of them are shared by presets that
disagree about `memory` -- so a title row records the majority value and the
host is told the match was approximate.

Usage:
  scripts/make-preset-db.py [--presets docs/dreamshell-presets] [--out FILE]
"""

import argparse
import collections
import os
import pathlib
import sys

FIELDS = ["memory", "async", "dma", "irq", "cdda", "heap", "low",
          "fastboot", "type", "mode", "altread", "pa1", "pv1", "pa2", "pv2"]

# The MD5 of 2048 zero bytes. Presets named this were saved after a
# boot-sector read that returned nothing, so the hash identifies "the read
# failed", not a game. Emitting them would make every such disc match one
# arbitrary game's settings.
ZERO_SECTOR_MD5 = "c99a74c555371a433d121f551d6c6398"


def load_cfg(path):
    out = {}
    with open(path, errors="replace") as fh:
        for line in fh:
            if "=" in line:
                key, value = line.split("=", 1)
                out[key.strip()] = value.strip()
    return out


def main():
    repo = pathlib.Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--presets", default=str(repo / "docs" / "dreamshell-presets"))
    ap.add_argument("--out", default=str(repo / "docs" / "game-presets.tsv"))
    args = ap.parse_args()

    cd_dir = pathlib.Path(args.presets) / "cd"
    if not cd_dir.is_dir():
        sys.exit(f"no cd/ under {args.presets}")

    rows = {}
    skipped_zero = 0
    for path in sorted(cd_dir.glob("cd_*.cfg")):
        # macOS resource forks travel with the archive and are not presets.
        if path.name.startswith("._"):
            continue
        md5 = path.name[len("cd_"):-len(".cfg")]
        if len(md5) != 32:
            continue
        cfg = load_cfg(path)
        if md5 == ZERO_SECTOR_MD5:
            skipped_zero += 1
            continue
        rows[md5] = cfg

    # Majority `memory` per title, for the fallback path. Ties break towards
    # the value the whole database prefers, which keeps the answer stable
    # instead of depending on directory order.
    overall = collections.Counter(r.get("memory", "") for r in rows.values())
    per_title = collections.defaultdict(collections.Counter)
    for r in rows.values():
        per_title[r.get("title", "")][r.get("memory", "")] += 1
    conflicted = {t for t, c in per_title.items() if len(c) > 1}

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", newline="\n") as fh:
        fh.write("# Generated by scripts/make-preset-db.py from DreamShell's isoldr\n"
                 "# presets (docs/dreamshell-presets). Do not edit by hand.\n"
                 "#\n"
                 "# One row per distinct boot-sector MD5, taken from the `cd` variant.\n"
                 "# `memory` is the address the loader must be linked at to stay out of\n"
                 "# that title's way; the rest is carried so the host can say what it is\n"
                 "# NOT honouring.\n"
                 "#\n"
                 "# md5\ttitle\t" + "\t".join(FIELDS) + "\n")
        for md5 in sorted(rows):
            r = rows[md5]
            title = r.get("title", "").replace("\t", " ")
            fh.write(md5 + "\t" + title + "\t"
                     + "\t".join(r.get(f, "") for f in FIELDS) + "\n")

    print(f"wrote {out} -- {len(rows)} rows, {len(per_title)} distinct titles")
    print(f"  skipped {skipped_zero} rows keyed on the all-zero boot sector")
    print(f"  {len(conflicted)} titles have presets that disagree about `memory`")
    print("  memory distribution: "
          + ", ".join(f"{m}={n}" for m, n in overall.most_common(8)))


if __name__ == "__main__":
    main()
